# Generated by Django 3.2 on 2021-04-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='id_my',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='userId',
            field=models.TextField(null=True),
        ),
    ]
