# Generated by Django 3.2 on 2021-05-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_delete_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='id_my',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='space',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
