# Generated by Django 3.2 on 2021-05-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210506_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='space',
            name='title',
            field=models.TextField(),
        ),
    ]
